name: Main Workflow
on:
  push:
    branches:
      - main
  schedule:
    - cron: '1,3,6,9,12,15,18,20,23,26,29,30,33,36,39,42,45,48,51,54,57,59 * * * *'

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      working-directory: ./bot/
    strategy:
      matrix:
        node-version: [16.13.0]

    steps:

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v4

    - name: Environment Preparation
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Dependencies Installation
      working-directory: ./bot/
      run: |
        npm install

    - name: Create env parameters
      working-directory: ./bot/
      run: |
        touch .env
        echo BLOCKCHAIN_CONNECTION_STRING=${{ secrets.BLOCKCHAIN_CONNECTION_STRING }} >> .env
        echo PINATA_JWT=${{ secrets.PINATA_JWT }} >> .env
        echo CHAT_ID=${{ secrets.CHAT_ID }} >> .env
        echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env

    - name: Build JSONs
      working-directory: ./bot/
      run: |
        npm run start